package utils

import "strings"

// helicopterTypes is an embedded map of ICAO type designators that are helicopters.
// Source: ICAO Doc 8643 + FAA aircraft database (helicopter designators).
var helicopterTypes = map[string]bool{
	"H60":   true,
	"S70":   true,
	"EC35":  true,
	"EC45":  true,
	"EC55":  true,
	"EC75":  true,
	"B06":   true,
	"B07":   true,
	"B12":   true,
	"B13":   true,
	"B47":   true,
	"B06T":  true,
	"B412":  true,
	"B427":  true,
	"B429":  true,
	"R22":   true,
	"R44":   true,
	"R66":   true,
	"S76":   true,
	"S92":   true,
	"S61":   true,
	"S58":   true,
	"S55":   true,
	"AW09":  true,
	"AW19":  true,
	"AW13":  true,
	"AW16":  true,
	"AW18":  true,
	"AW10":  true,
	"NH90":  true,
	"CH47":  true,
	"V22":   true,
	"MH60":  true,
	"AS32":  true,
	"AS35":  true,
	"AS55":  true,
	"AS65":  true,
	"BO10":  true,
	"BK17":  true,
	"EC20":  true,
	"EC25":  true,
	"EC30":  true,
	"EC65":  true,
	"H145":  true,
	"H160":  true,
	"H125":  true,
	"H130":  true,
	"H135":  true,
	"H175":  true,
	"H215":  true,
	"H225":  true,
	"MD52":  true,
	"MD60":  true,
	"MD90":  true,
	"HU1":   true,
	"UH1":   true,
	"UH60":  true,
	"CH53":  true,
	"SH60":  true,
	"HH60":  true,
	"AH64":  true,
	"OH58":  true,
	"A119":  true,
	"A109":  true,
	"AB47":  true,
	"AB06":  true,
	"AB12":  true,
	"AB41":  true,
	"KA26":  true,
	"KA27":  true,
	"KA32":  true,
	"KA50":  true,
	"KA52":  true,
	"MI8":   true,
	"MI17":  true,
	"MI24":  true,
	"MI26":  true,
	"MI28":  true,
	"W3":    true,
	"SW4":   true,
	"SK76":  true,
	"SK92":  true,
	"H500":  true,
	"H369":  true,
	"OH6":   true,
	"LH10":  true,
	"SA31":  true,
	"SA34":  true,
	"SA36":  true,
	"SA37":  true,
	"EU30":  true,
	"EU35":  true,
	"EU45":  true,
	"EU55":  true,
	"EU65":  true,
	"HELI":  true,
	"GYRO":  true,
	"ROTO":  true,
	"UHEL":  true,
	"MHEL":  true,
	"COAX":  true,
	"TAND":  true,
	"CH46":  true,
	"HH65":  true,
	"MH65":  true,
	"SA32":  true,
	"MI2":   true,
	"MI4":   true,
	"MI6":   true,
	"Z9":    true,
	"Z10":   true,
	"Z15":   true,
	"Z19":   true,
	"K136":  true,
	"AW609": true,
	"ALH":   true,
	"LCH":   true,
	"LUH":   true,
	"206B":  true,
	"206L":  true,
	"H407":  true,
	"F28F":  true,
	"480B":  true,
	"SBL1":  true,
	"S300":  true,
	"S330":  true,
	"S333":  true,
	"HNZ1":  true,
	"HNZ2":  true,
	"MBUS":  true,
	"MKAM":  true,
	"MMIL":  true,
	"MBEL":  true,
	"MSIK":  true,
	"MAGU":  true,
	"MLIN":  true,
	"RAH66": true,
	"MI":    true,
}

// IsHelicopter returns true if the given ICAO type code represents a helicopter.
// Lookup is case-insensitive.
func IsHelicopter(typeCode string) bool {
	if typeCode == "" {
		return false
	}
	return helicopterTypes[strings.ToUpper(typeCode)]
}

// AircraftCategory returns "helicopter" or "plane" based on the ICAO type code.
func AircraftCategory(typeCode string) string {
	if IsHelicopter(typeCode) {
		return "helicopter"
	}
	return "plane"
}
