/**
 * Static planet data — physical properties, orbital elements, and descriptions.
 * All values sourced from NASA Planetary Fact Sheets.
 */

export const PLANET_DATA = {
  mercury: {
    title:       'Mercury',
    type:        'Terrestrial',
    typeColor:   '#c0826a',
    symbol:      '☿',
    distanceAU:  0.387,
    distanceKM:  57_900_000,
    periodDays:  87.97,
    dayHours:    1407.6,
    diameterKM:  4_879,
    massEarth:   0.0553,
    gravity:     0.38,
    moons:       0,
    moonNames:   [],
    tempMin:     -180,
    tempMax:     430,
    atmosphere:  'Virtually none — trace O₂, Na, H₂',
    color:       '#b5b5b5',
    facts:       'The smallest planet and closest to the Sun. Its extremely thin exosphere offers no insulation, causing the most extreme temperature swings in the solar system — from 430 °C at noon to −180 °C at night. Despite its proximity to the Sun, Mercury is not the hottest planet.',
  },
  venus: {
    title:       'Venus',
    type:        'Terrestrial',
    typeColor:   '#c0826a',
    symbol:      '♀',
    distanceAU:  0.723,
    distanceKM:  108_200_000,
    periodDays:  224.7,
    dayHours:    5832.5,
    diameterKM:  12_104,
    massEarth:   0.815,
    gravity:     0.91,
    moons:       0,
    moonNames:   [],
    tempMin:     462,
    tempMax:     465,
    atmosphere:  'CO₂ 96.5%, N₂ 3.5%, trace SO₂',
    color:       '#e8cfa0',
    facts:       'The hottest planet in the solar system — its dense CO₂ atmosphere creates a runaway greenhouse effect, keeping surface temperatures at ~465 °C regardless of day or night. It rotates backwards and so slowly that a Venusian day is longer than its year.',
  },
  earth: {
    title:       'Earth',
    type:        'Terrestrial',
    typeColor:   '#c0826a',
    symbol:      '🜨',
    distanceAU:  1.000,
    distanceKM:  149_600_000,
    periodDays:  365.25,
    dayHours:    23.93,
    diameterKM:  12_742,
    massEarth:   1.000,
    gravity:     1.00,
    moons:       1,
    moonNames:   ['Moon'],
    tempMin:     -88,
    tempMax:     58,
    atmosphere:  'N₂ 78.1%, O₂ 20.9%, Ar 0.9%, CO₂ 0.04%',
    color:       '#4a9eff',
    facts:       'The only known planet to harbour life, liquid surface water, and a protective magnetic field. Its large Moon stabilises Earth\'s axial tilt, moderating climate over geological timescales. Currently home to ~8.1 billion people and millions of tracked aircraft.',
  },
  mars: {
    title:       'Mars',
    type:        'Terrestrial',
    typeColor:   '#c0826a',
    symbol:      '♂',
    distanceAU:  1.524,
    distanceKM:  227_900_000,
    periodDays:  686.97,
    dayHours:    24.62,
    diameterKM:  6_779,
    massEarth:   0.107,
    gravity:     0.38,
    moons:       2,
    moonNames:   ['Phobos', 'Deimos'],
    tempMin:     -125,
    tempMax:     20,
    atmosphere:  'CO₂ 95.3%, N₂ 2.7%, Ar 1.6%',
    color:       '#d66b4f',
    facts:       'Home to Olympus Mons — the largest volcano in the solar system at 21 km high — and Valles Marineris, a canyon system 4,000 km long. Evidence of ancient rivers and a thicker atmosphere suggest Mars was once habitable. Current target of human exploration missions.',
  },
  jupiter: {
    title:       'Jupiter',
    type:        'Gas Giant',
    typeColor:   '#7a9abf',
    symbol:      '♃',
    distanceAU:  5.203,
    distanceKM:  778_500_000,
    periodDays:  4332.6,
    dayHours:    9.93,
    diameterKM:  139_820,
    massEarth:   317.8,
    gravity:     2.53,
    moons:       95,
    moonNames:   ['Io', 'Europa', 'Ganymede', 'Callisto'],
    tempAvg:     -108,
    atmosphere:  'H₂ 89.8%, He 10.2%, trace CH₄, NH₃',
    color:       '#c88b3a',
    facts:       'The largest planet — more than twice the mass of all other planets combined. Its Great Red Spot is a storm larger than Earth that has raged for over 350 years. Europa, one of its 95 moons, has a subsurface ocean and is considered one of the best candidates for extraterrestrial life.',
  },
  saturn: {
    title:       'Saturn',
    type:        'Gas Giant',
    typeColor:   '#7a9abf',
    symbol:      '♄',
    distanceAU:  9.537,
    distanceKM:  1_432_000_000,
    periodDays:  10756,
    dayHours:    10.66,
    diameterKM:  116_460,
    massEarth:   95.2,
    gravity:     1.07,
    moons:       146,
    moonNames:   ['Titan', 'Enceladus', 'Mimas', 'Rhea'],
    tempAvg:     -138,
    atmosphere:  'H₂ 96.3%, He 3.3%, trace CH₄',
    color:       '#e4d191',
    facts:       'Its iconic rings — made of ice and rock from centimetres to tens of metres — extend up to 282,000 km but are only ~10 m thick. Saturn is the least dense planet, less dense than water. Titan, its largest moon, has a thick atmosphere and liquid methane lakes.',
  },
  uranus: {
    title:       'Uranus',
    type:        'Ice Giant',
    typeColor:   '#5ab8b8',
    symbol:      '⛢',
    distanceAU:  19.19,
    distanceKM:  2_867_000_000,
    periodDays:  30589,
    dayHours:    17.24,
    diameterKM:  50_724,
    massEarth:   14.5,
    gravity:     0.89,
    moons:       28,
    moonNames:   ['Miranda', 'Ariel', 'Umbriel', 'Titania', 'Oberon'],
    tempAvg:     -195,
    atmosphere:  'H₂ 82.5%, He 15.2%, CH₄ 2.3%',
    color:       '#7de8e8',
    facts:       'Uranus rotates on its side — its axial tilt is 98°, meaning it essentially rolls around the Sun. This gives it extreme seasons where each pole experiences 42 years of continuous sunlight followed by 42 years of darkness. Its blue-green colour comes from methane absorbing red light.',
  },
  neptune: {
    title:       'Neptune',
    type:        'Ice Giant',
    typeColor:   '#5ab8b8',
    symbol:      '♆',
    distanceAU:  30.07,
    distanceKM:  4_515_000_000,
    periodDays:  59800,
    dayHours:    16.11,
    diameterKM:  49_244,
    massEarth:   17.1,
    gravity:     1.14,
    moons:       16,
    moonNames:   ['Triton', 'Proteus', 'Nereid'],
    tempAvg:     -200,
    atmosphere:  'H₂ 80%, He 19%, CH₄ 1.5%',
    color:       '#3f54ba',
    facts:       'The windiest planet — supersonic winds up to 2,100 km/h. Its largest moon Triton orbits in the opposite direction to Neptune\'s rotation, suggesting it was a captured Kuiper Belt object. Neptune was the first planet discovered through mathematical prediction rather than direct observation.',
  },
}
